export const fallbackWorlds = [
  {
    publicId: 'rXba2ymnB-nx',
    title: 'Interdimensional Chaos Trip',
    worldName: 'Interdimensional Chaos Trip',
    description: 'A chaotic, high-stakes interdimensional adventure where every audience choice drives the danger.',
    type: 'show',
    status: 'sleeping',
    viewerCount: null,
    thumbnailUrl: '',
    worldLogoUrl: '',
    demoVideoEnabled: false,
    demoVideoUrl: '',
  },
  {
    publicId: 'CVyQbC5FNCcE',
    title: 'Timmy’s Adventures',
    worldName: 'Timmy’s Adventures',
    description: 'Navigate a haunting, physics-driven silhouette wasteland where every shadow hides a deadly puzzle.',
    type: 'game',
    status: 'sleeping',
    viewerCount: null,
    thumbnailUrl: '',
    worldLogoUrl: '',
    demoVideoEnabled: false,
    demoVideoUrl: '',
  },
  {
    publicId: '0kN1wkIqfYlr',
    title: 'Space Mission',
    worldName: 'Space Mission',
    description: 'Step into the boots of an elite armored operative on a war-torn alien frontier.',
    type: 'game',
    status: 'sleeping',
    viewerCount: null,
    thumbnailUrl: '',
    worldLogoUrl: '',
    demoVideoEnabled: false,
    demoVideoUrl: '',
  },
  {
    publicId: 'ucBQS93o8a2b',
    title: 'Magic Chronicles',
    worldName: 'Magic Chronicles',
    description: 'A whimsical, high-stakes journey across a vibrant post-apocalyptic continent.',
    type: 'show',
    status: 'sleeping',
    viewerCount: null,
    thumbnailUrl: '',
    worldLogoUrl: '',
    demoVideoEnabled: false,
    demoVideoUrl: '',
  },
  {
    publicId: 'Yn80W-no-Ox7',
    title: 'Skybound Chase',
    worldName: 'Skybound Chase',
    description: 'Hunt ancient beasts and soar through breathtaking canyon skies in an open-world aerial adventure.',
    type: 'game',
    status: 'sleeping',
    viewerCount: null,
    thumbnailUrl: '',
    worldLogoUrl: '',
    demoVideoEnabled: false,
    demoVideoUrl: '',
  },
  {
    publicId: 'W2oWIF1vIZeA',
    title: 'Abyssal Tide',
    worldName: 'Abyssal Tide',
    description: 'Explore a bioluminescent alien archipelago guided by the choices of its viewers.',
    type: 'show',
    status: 'sleeping',
    viewerCount: null,
    thumbnailUrl: '',
    worldLogoUrl: '',
    demoVideoEnabled: false,
    demoVideoUrl: '',
  },
];
